name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, test ]
  pull_request:
    branches: [ main, dev, test ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: transporte_test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: mvn -B clean compile
      
    - name: Run Unit Tests
      run: mvn -B test
      
    - name: Run Integration Tests
      run: mvn -B verify -P integration-test
      
    - name: Check Test Coverage
      run: |
        mvn jacoco:report
        echo "Verificando cobertura mínima del 80%"
        mvn jacoco:check -Djacoco.minimum.coverage=0.80

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./target/site/jacoco/jacoco.xml
        fail_ci_if_error: true

    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      run: docker build -t transporte-app .

    - name: Run Security Scan
      uses: aquasecurity/trivy-action@master
      if: github.ref == 'refs/heads/main'
      with:
        image-ref: 'transporte-app'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    # --- Publicar artefactos de pruebas y cobertura ---
    - name: Publicar reportes de pruebas (JUnit)
      uses: actions/upload-artifact@v3
      with:
        name: junit-reports
        path: |
          target/surefire-reports/
          target/failsafe-reports/

    - name: Publicar reporte de cobertura (JaCoCo HTML)
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-html
        path: target/site/jacoco/

    - name: Publicar reporte de cobertura (JaCoCo XML)
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-xml
        path: target/site/jacoco/jacoco.xml

    - name: Mostrar resultados de pruebas en GitHub
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit 