name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: transporte_test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      run: mvn -B verify
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./target/site/jacoco/jacoco.xml
        fail_ci_if_error: true

    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      run: docker build -t transporte-app .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      if: github.ref == 'refs/heads/main'
      with:
        image-ref: 'transporte-app'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH' 